### ISSUE TITLE
Version 0.3.2 Incompatible with Thunderbird 38.2.0

### ISSUE THREAD

**Issue by dicconspain** [alxlit/elementary-thunderbird#22]
Thunderbird disables add-on with message:

> elementary Thunderbird is incompatible with Thunderbird 38.2.0

See attached screen grab of add-ons Manager tab:

![elementary_thunderbird_incompatible_with_38-2-0](https://cloud.githubusercontent.com/assets/9283452/9517000/72a0cd1a-4ca4-11e5-8fb8-925c3987041a.png)

**Comment by alxlit** [comment]
I've sent an update (#21), it just needs to get reviewed by the addons team. Was queue position 159 last night so it might take a little while.

**Comment by alxlit** [comment]
Looks like it's up.
